/* src\App.svelte generated by Svelte v3.23.2 */
import {
	SvelteComponent,
	create_component,
	destroy_component,
	init,
	mount_component,
	noop,
	safe_not_equal,
	transition_in,
	transition_out
} from "../web_modules/svelte/internal.js";

import CarGame from "./CarGame.js";
import Spaceships from "./Spaceships.js";

function create_fragment(ctx) {
	let cargame;
	let current;
	cargame = new CarGame({});

	return {
		c() {
			create_component(cargame.$$.fragment);
		},
		m(target, anchor) {
			mount_component(cargame, target, anchor);
			current = true;
		},
		p: noop,
		i(local) {
			if (current) return;
			transition_in(cargame.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(cargame.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(cargame, detaching);
		}
	};
}

class App extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default App;